[package]
name = "cli_pass_manager_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = "0.24.0"
crossterm = "0.27.0"
arboard = "3.3.0"